"""rename usuarios password to hashed_password

Revision ID: 665e42752cd6
Revises: 6bcf9399c53e
Create Date: 2026-02-28 22:09:19.578430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '665e42752cd6'
down_revision: Union[str, None] = '6bcf9399c53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.drop_column('usuarios', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('usuarios', 'hashed_password')
    # ### end Alembic commands ###
