"""initial schema

Revision ID: 6bcf9399c53e
Revises: 
Create Date: 2026-02-28 17:45:41.272031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bcf9399c53e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pontos_amostragem',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('desc_uso_solo', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='pontos_amostragem_latitude_check'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='pontos_amostragem_longitude_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pontos_amostragem_desc_uso_solo'), 'pontos_amostragem', ['desc_uso_solo'], unique=False)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('preco >= 0', name='produtos_preco_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('movimentacoes_caixa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), sa.Computed('quantidade * valor_unitario', persisted=True), nullable=False),
    sa.Column('tipo_movimentacao', sa.Enum('entrada', 'saida', name='tipo_movimentacao_enum'), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantidade > 0', name='movimentacoes_caixa_quantidade_check'),
    sa.CheckConstraint('valor_unitario >= 0', name='movimentacoes_caixa_valor_unitario_check'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimentacoes_caixa_produto_id'), 'movimentacoes_caixa', ['produto_id'], unique=False)
    op.create_index(op.f('ix_movimentacoes_caixa_tipo_movimentacao'), 'movimentacoes_caixa', ['tipo_movimentacao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimentacoes_caixa_tipo_movimentacao'), table_name='movimentacoes_caixa')
    op.drop_index(op.f('ix_movimentacoes_caixa_produto_id'), table_name='movimentacoes_caixa')
    op.drop_table('movimentacoes_caixa')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_pontos_amostragem_desc_uso_solo'), table_name='pontos_amostragem')
    op.drop_table('pontos_amostragem')
    # ### end Alembic commands ###
