"""refatora quantidade estoque

Revision ID: f4a8865a0ad8
Revises: e258c5ce599b
Create Date: 2026-03-01 19:01:57.745077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4a8865a0ad8'
down_revision: Union[str, None] = 'e258c5ce599b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movimentacoes_caixa', 'created_at')
    op.add_column('produtos', sa.Column('quantidade_estoque', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('produtos', 'descricao',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('produtos', 'descricao',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('produtos', 'quantidade_estoque')
    op.add_column('movimentacoes_caixa', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
